### ISSUE TITLE
sequence clustering

### ISSUE THREAD

**Issue by jspmccain** [GuyAllard/markov_clustering#10]
Super excited that you've put this work into a python MCL approach! Do you know if the input can be sequences? I'm assuming you first need to do a sequence similarity matrix?

Thanks!

**Comment by GuyAllard** [comment]
Hi Scott,
The module does not directly work directly with sequences, but instead operates on similarity matrices which you must generate using other tools.
I use it for clustering DNA sequencing data, first using alignment tools to construct the similarity matrix.

Guy

**Comment by jspmccain** [comment]
Thanks Guy!

It would be really helpful to see how you've been going from sequence similarity matrix to the input to run_mcl! Working away on it now - but feel like I'm not doing the most efficient approach. 

Right now I'm taking BLAST bit scores (the ratio of bit score to self-hit bit score) to create an all-vs-all sequence similarity matrix, and then planning on writing a numpy array, converting to a networkx graph, then to a sparse adjacency matrix.
