### ISSUE TITLE
Error Plotting

### ISSUE THREAD

**Issue by EdbertTheda** [GuyAllard/markov_clustering#12]
When I code mc.draw_graph(matrix, clusters, pos=positions, node_size=50, with_labels=False, edge_color="silver"). it gets error : AttributeError: module 'matplotlib.cm' has no attribute 'tab20'.
How do I fix this? thank you

**Comment by GuyAllard** [comment]
Can you check the version of matplotlib that you are using, and update it to a recent version if necessary?

**Comment by GuyAllard** [comment]
This issue is probably caused by outdated dependencies on the users machine.
