### ISSUE TITLE
AttributeError: module 'markov_clustering' has no attribute 'draw_graph'

### ISSUE THREAD

**Issue by kzorina** [GuyAllard/markov_clustering#13]
When I run this piece of code:
```
result = mc.run_mcl(graph_matrix_sparse, inflation=1.4)
clusters = mc.get_clusters(result)
mc.draw_graph(matrix, clusters, pos=positions, node_size=50, with_labels=False, edge_color="silver")
```

I get message 
```
----> 8 mc.draw_graph(matrix, clusters, pos=positions, node_size=50, with_labels=False, edge_color="silver")

AttributeError: module 'markov_clustering' has no attribute 'draw_graph'
```

markov-clustering-0.0.6.dev0   ( tried markov-clustering-0.0.5.dev0  too)
python==3.6

**Comment by GuyAllard** [comment]
Hi,
Did you install with visualization support using
```pip install markov_clustering[drawing]``` ?

The visualization is an optional utility as it does not form part of the core algorithm.

**Comment by kzorina** [comment]
@GuyAllard Thank you! I missed this step. Now graph is fine.
