### ISSUE TITLE
AttributeError: module 'markov_clustering' has no attribute 'run_mcl'

### ISSUE THREAD

**Issue by saini5** [GuyAllard/markov_clustering#5]
Hi, 
I installed your package using pip as stated on the readme, but can't get the example script running.
I guess it can't find the run_mcl method/function. 

The error is:
AttributeError: module 'markov_clustering' has no attribute 'run_mcl'

Is there a problem in the released version of the package? or if no, can you suggest how I can fix this?
I'm using Python 3.5

Thanks

**Comment by GuyAllard** [comment]
Hi,

Can you confirm the python version that you are using, e.g.  
from the command line,
```python --version```

And also the version of markov_clustering that you are using, e.g.  
```
python
>>>import markov_clustering
>>>markov_clustering.__version__
```

**Comment by saini5** [comment]
Hi,
Python 3.5.2
Markov clustering version: 0.0.3.dev

**Comment by saini5** [comment]
Ok, so one thing I did was to upgrade my pip version from 9.0.1 to 10.0.1 because I saw you bumped up the pip version in github. I was still running into the issue after restarting pycharm.
I restarted my windows and the issue seems to be resolved.

Now, I'm running into the issue raised by another person (#4 )

But I'll request you to keep this issue open for another day or two, in case I run into the problem again.
Hope you can resolve the #4 issue(matplotlib window disappearing) quickly.

Thanks!

**Comment by GuyAllard** [comment]
I hate it when things magically resolve themselves!
Anyway, I will leave this issue open for a bit, hopefully you do not encounter this again.

**Comment by GuyAllard** [comment]
I'm closing this issue as it has not re-occurred.
We can re-open it if necessary.

**Comment by twesleyb** [comment]
I had this same issue, 
``` AttributeError: module 'markov_clustering' has no attribute 'run_mcl' ```

I'm not sure why I have this issue, but I was able to fix it by explicitly importing the modules I needed from the __markov_clustering__ library, for example:
```
from markov_clustering import run_mcl
from markov_clustering import get_clusters
```

Posting in case anyone else has this same issue and comes across this thread.
